//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package common

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIMasterSpec) DeepCopyInto(out *AIMasterSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.JobMonitorPolicy != nil {
		in, out := &in.JobMonitorPolicy, &out.JobMonitorPolicy
		*out = new(JobMonitorPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIMasterSpec.
func (in *AIMasterSpec) DeepCopy() *AIMasterSpec {
	if in == nil {
		return nil
	}
	out := new(AIMasterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobMonitorPolicy) DeepCopyInto(out *JobMonitorPolicy) {
	*out = *in
	if in.EnableJobRestart != nil {
		in, out := &in.EnableJobRestart, &out.EnableJobRestart
		*out = new(bool)
		**out = **in
	}
	if in.MaxNumOfJobRestart != nil {
		in, out := &in.MaxNumOfJobRestart, &out.MaxNumOfJobRestart
		*out = new(int32)
		**out = **in
	}
	if in.ExecutionMode != nil {
		in, out := &in.ExecutionMode, &out.ExecutionMode
		*out = new(string)
		**out = **in
	}
	if in.MaxToleratedFailureRate != nil {
		in, out := &in.MaxToleratedFailureRate, &out.MaxToleratedFailureRate
		*out = new(string)
		**out = **in
	}
	if in.EnableLogHangDetection != nil {
		in, out := &in.EnableLogHangDetection, &out.EnableLogHangDetection
		*out = new(bool)
		**out = **in
	}
	if in.LogHangIntervalInSeconds != nil {
		in, out := &in.LogHangIntervalInSeconds, &out.LogHangIntervalInSeconds
		*out = new(int32)
		**out = **in
	}
	if in.EnablePodCompletedDetection != nil {
		in, out := &in.EnablePodCompletedDetection, &out.EnablePodCompletedDetection
		*out = new(bool)
		**out = **in
	}
	if in.PodCompletedIntervalInSeconds != nil {
		in, out := &in.PodCompletedIntervalInSeconds, &out.PodCompletedIntervalInSeconds
		*out = new(int32)
		**out = **in
	}
	if in.EnableLogDirectToNas != nil {
		in, out := &in.EnableLogDirectToNas, &out.EnableLogDirectToNas
		*out = new(bool)
		**out = **in
	}
	if in.MaxNumOfSameError != nil {
		in, out := &in.MaxNumOfSameError, &out.MaxNumOfSameError
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobMonitorPolicy.
func (in *JobMonitorPolicy) DeepCopy() *JobMonitorPolicy {
	if in == nil {
		return nil
	}
	out := new(JobMonitorPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobStatus) DeepCopyInto(out *JobStatus) {
	*out = *in
	in.JobStatus.DeepCopyInto(&out.JobStatus)
	out.AIMasterStatus = in.AIMasterStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobStatus.
func (in *JobStatus) DeepCopy() *JobStatus {
	if in == nil {
		return nil
	}
	out := new(JobStatus)
	in.DeepCopyInto(out)
	return out
}
