# Generate dev docker image: alideeprec/deeprec-dev:deeprec-extension-cpu-py36-ubuntu18.04
FROM alideeprec/deeprec-base:deeprec-base-cpu-py36-ubuntu18.04

RUN apt-get update
RUN apt-get install -y autoconf
RUN apt-get install -y libssl-dev libc-ares-dev

# build & install deeprec wheel manually
COPY ./tensorflow-1.15.5+deeprec2402-cp36-cp36m-linux_x86_64.whl /root/tensorflow-1.15.5+deeprec2402-cp36-cp36m-linux_x86_64.whl
COPY ./tensorflow_estimator-1.15.2+deeprec2310-py2.py3-none-any.whl /root/tensorflow_estimator-1.15.2+deeprec2310-py2.py3-none-any.whl
RUN pip install /root/tensorflow-1.15.5+deeprec2402-cp36-cp36m-linux_x86_64.whl
RUN pip install /root/tensorflow_estimator-1.15.2+deeprec2310-py2.py3-none-any.whl
