# permissions for end users to view tfjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tfjob-viewer-role
rules:
- apiGroups:
  - training.pai.ai
  resources:
  - tfjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - training.pai.ai
  resources:
  - tfjobs/status
  verbs:
  - get
