# permissions for end users to edit tfjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tfjob-editor-role
rules:
- apiGroups:
  - training.pai.ai
  resources:
  - tfjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - training.pai.ai
  resources:
  - tfjobs/status
  verbs:
  - get
